name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore: # 下列文件的变更不触发部署
      - LICENSE
      - README.md
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0 
      - name: Setup Node  🎬
        uses: actions/setup-node@main
        with:
          node-version: "lts/*"
<<<<<<< HEAD
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.4.0
          dest: # optional, default is ~/setup-pnpm
          run_install: true 
      - name: Build 🔧 
        run: |
          pnpm install
          pnpm run build
          pnpm run generate
=======
      - name: Build 🔧 
        run: |
          npm install
          npm run build
          npm run generate
>>>>>>> 4494ca5 (test: test deploy action)
          ls -lrth
      - name: Deploy 🚀 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DEPLOY_TOKEN }} 
          branch: gh-pages
          folder: dist